### ISSUE TITLE
A message (TEMPORAL DEPENDENCY)

### ISSUE THREAD

**Issue by Momoyeyu** [ruby11dog/audio-adversarial-example#1]
## Issue:
您好，我在`2019-CHARACTERIZING AUDIO ADVERSARIAL EXAMPLES USING TEMPORAL DEPENDENCY`文章的repo中看到您的issue，issue已经close了所以我估计您已经成功复现了此篇文章，我现在遇到了一些麻烦，具体如下：

- 我现在正在复现TD这篇文章，但是遇到了各种问题导致跑不通代码，主要是因为tf_logits3文件。  
- 根据代码注释我估计这篇文章使用了Carlini某篇文章的decoder，但不知道是哪一篇，我看到您fork了与此repo同名的repo，其中有一个get_logits文件，我便使用了那个文件，可是还是遇到了许多无法解决的问题。比如下图：
<img width="1280" alt="76e31dc832cf873360aeb6c4d2a9edd" src="https://github.com/user-attachments/assets/7c1c5c70-6e5d-4dcd-8334-cf68d6632e1f">

- 此外，我下载了DeepSpeech 0.4.1，但其中有一项依赖缺失，如下：
`from tensorflow.contrib.lite.python import tflite_convert`

- 为了先跑通代码我将使用条引用的代码注释掉了，可惜还是遇到了前述的问题，如果您解决过这个依赖问题那就太好了。

如果您成功复现了这篇文章，请问能否将您的代码分享一下，我的邮箱是`momoyeyu@outlook.com`，期待您的回复。

**Comment by ruby11dog** [comment]
> ## Issue:
> 您好，我在`2019-CHARACTERIZING AUDIO ADVERSARIAL EXAMPLES USING TEMPORAL DEPENDENCY`文章的repo中看到您的issue，issue已经close了所以我估计您已经成功复现了此篇文章，我现在遇到了一些麻烦，具体如下：
> 
> * 我现在正在复现TD这篇文章，但是遇到了各种问题导致跑不通代码，主要是因为tf_logits3文件。
> * 根据代码注释我估计这篇文章使用了Carlini某篇文章的decoder，但不知道是哪一篇，我看到您fork了与此repo同名的repo，其中有一个get_logits文件，我便使用了那个文件，可是还是遇到了许多无法解决的问题。比如下图：
> 
> <img alt="76e31dc832cf873360aeb6c4d2a9edd" width="1280" src="https://private-user-images.githubusercontent.com/115639149/352799025-7c1c5c70-6e5d-4dcd-8334-cf68d6632e1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDI2ODksIm5iZiI6MTcyMjI0MjM4OSwicGF0aCI6Ii8xMTU2MzkxNDkvMzUyNzk5MDI1LTdjMWM1YzcwLTZlNWQtNGRjZC04MzM0LWNmNjhkNjYzMmUxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwODM5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJlYjJhNDkyOTMxYTEyMGI2ZGY2YzA2NTJmYjU1MWM5ZjA4NmI0ZmU4NmVlZjJhMDE1OWYzZTVjYTU2MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.INcptiunJk0fQQfMFTvIdKMq_N-U1Fhr0KlHuJ4Qiqo">
> * 此外，我下载了DeepSpeech 0.4.1，但其中有一项依赖缺失，如下：
>   `from tensorflow.contrib.lite.python import tflite_convert`
> * 为了先跑通代码我将使用条引用的代码注释掉了，可惜还是遇到了前述的问题，如果您解决过这个依赖问题那就太好了。
> 
> 如果您成功复现了这篇文章，请问能否将您的代码分享一下，我的邮箱是`momoyeyu@outlook.com`，期待您的回复。

不好意思，这个代码太过久远了，我已经没有当时的环境了，并且deepspeech也有点太老了，我建议你可以在较新的开源asr上尝试TD那篇文章的方法，逻辑不是很复杂的

**Comment by Momoyeyu** [comment]
> > ## Issue:
> > 您好，我在`2019-CHARACTERIZING AUDIO ADVERSARIAL EXAMPLES USING TEMPORAL DEPENDENCY`文章的repo中看到您的issue，issue已经close了所以我估计您已经成功复现了此篇文章，我现在遇到了一些麻烦，具体如下：
> > 
> > * 我现在正在复现TD这篇文章，但是遇到了各种问题导致跑不通代码，主要是因为tf_logits3文件。
> > * 根据代码注释我估计这篇文章使用了Carlini某篇文章的decoder，但不知道是哪一篇，我看到您fork了与此repo同名的repo，其中有一个get_logits文件，我便使用了那个文件，可是还是遇到了许多无法解决的问题。比如下图：
> > 
> > <img alt="76e31dc832cf873360aeb6c4d2a9edd" width="1280" src="https://private-user-images.githubusercontent.com/115639149/352799025-7c1c5c70-6e5d-4dcd-8334-cf68d6632e1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDI2ODksIm5iZiI6MTcyMjI0MjM4OSwicGF0aCI6Ii8xMTU2MzkxNDkvMzUyNzk5MDI1LTdjMWM1YzcwLTZlNWQtNGRjZC04MzM0LWNmNjhkNjYzMmUxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwODM5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTJlYjJhNDkyOTMxYTEyMGI2ZGY2YzA2NTJmYjU1MWM5ZjA4NmI0ZmU4NmVlZjJhMDE1OWYzZTVjYTU2MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.INcptiunJk0fQQfMFTvIdKMq_N-U1Fhr0KlHuJ4Qiqo">
> > * 此外，我下载了DeepSpeech 0.4.1，但其中有一项依赖缺失，如下：
> >   `from tensorflow.contrib.lite.python import tflite_convert`
> > * 为了先跑通代码我将使用条引用的代码注释掉了，可惜还是遇到了前述的问题，如果您解决过这个依赖问题那就太好了。
> > 如果您成功复现了这篇文章，请问能否将您的代码分享一下，我的邮箱是`momoyeyu@outlook.com`，期待您的回复。
> 
> 不好意思，这个代码太过久远了，我已经没有当时的环境了，并且deepspeech也有点太老了，我建议你可以在较新的开源asr上尝试TD那篇文章的方法，逻辑不是很复杂的

好的，感谢建议。
